version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins/2.176.1
    ports:
      - 1220:22/tcp
      - 1121:8080/tcp
    networks:
      ansible:
        ipv4_address: 192.168.250.254
    volumes:
      - /Users/adam.chen/Docker_Lab/abc/automation/python:/root/utility
    privileged: true
    container_name: jenkins
    hostname: jenkins

  lab-01:
    build:
      context: .
      dockerfile: Dockerfile.lab
    image: lab/centos7.6:1.1
    ports:
      - 1222:22/tcp
    networks:
      - ansible
    privileged: true
    container_name: lab-01
    hostname: lab-01

  lab-02:
    build:
      context: .
      dockerfile: Dockerfile.lab
    image: lab/centos7.6:1.1
    ports:
      - 1223:22/tcp
    networks:
      - ansible
    privileged: true
    container_name: lab-02
    hostname: lab-02
    
  lab-03:
    build:
      context: .
      dockerfile: Dockerfile.lab
    image: lab/centos7.6:1.1
    ports:
      - 1224:22/tcp
    networks:
      - ansible
    privileged: true
    container_name: lab-03
    hostname: lab-03
 
networks:
  ansible:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: "192.168.250.0/24"

